# Generated by Django 3.2.7 on 2021-09-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('url', models.URLField(blank=True, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
