# Generated by Django 3.2.7 on 2021-09-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210913_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
        migrations.AddField(
            model_name='song',
            name='lyricsURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
