# Generated by Django 3.2.7 on 2021-10-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210913_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youTubeVideoID',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
